function sample<T>(inputArray: T[], sampleSize: number): T[] {
  return inputArray
    .map<[T, number]>((item) => [item, Math.random()])
    .sort((a, b) => (a[1] < b[1] ? -1 : 1))
    .slice(0, sampleSize)
    .map((item) => item[0])
}

export function getCities(amount: number = 10) {
  const cities = [
    'Honolulu (USA)',
    'Maui (USA)',
    'Hilo (USA)',
    'Kailua-Kona (USA)',
    'Lahaina (USA)',
    'Nassau (Bahamas)',
    'Freeport (Bahamas)',
    'George Town (Bahamas)',
    'Marsh Harbour (Bahamas)',
    'San Juan (Puerto Rico)',
    'Ponce (Puerto Rico)',
    'Fajardo (Puerto Rico)',
    'Culebra (Puerto Rico)',
    'Vieques (Puerto Rico)',
    'Oranjestad (Aruba)',
    'Noord (Aruba)',
    'Palm Beach (Aruba)',
    'Philipsburg (Sint Maarten)',
    'Marigot (Saint Martin)',
    'Road Town (British Virgin Islands)',
    'Tortola (British Virgin Islands)',
    'Jost Van Dyke (British Virgin Islands)',
    'Anegada (British Virgin Islands)',
    'Virgin Gorda (British Virgin Islands)',
    'Gustavia (Saint Barthelemy)',
    'Basseterre (Saint Kitts and Nevis)',
    'Charlestown (Saint Kitts and Nevis)',
    'Kingston (Jamaica)',
    'Ocho Rios (Jamaica)',
    'Montego Bay (Jamaica)',
    'Negril (Jamaica)',
    'Port Antonio (Jamaica)',
    'Port of Spain (Trinidad and Tobago)',
    'Scarborough (Trinidad and Tobago)',
    'Castries (Saint Lucia)',
    'Soufriere (Saint Lucia)',
    'Rodney Bay (Saint Lucia)',
    'Fort-de-France (Martinique)',
    'Saint-Pierre (Martinique)',
    "St. George's (Grenada)",
    'Grand Anse (Grenada)',
    'Basse-Terre (Guadeloupe)',
    'Pointe-a-Pitre (Guadeloupe)',
    'Roseau (Dominica)',
    'Portsmouth (Dominica)',
    'Bridgetown (Barbados)',
    'Holetown (Barbados)',
    'Speightstown (Barbados)',
    'Hamilton (Bermuda)',
    "St. George's (Bermuda)",
    'Victoria (Seychelles)',
    'Mahebourg (Mauritius)',
    'Grand Baie (Mauritius)',
    'Port Louis (Mauritius)',
    'Flic en Flac (Mauritius)',
    'Curepipe (Mauritius)',
    'Saint-Denis (Reunion)',
    'Saint-Paul (Reunion)',
    'Saint-Pierre (Reunion)',
    'Le Tampon (Reunion)',
    'Mamoudzou (Mayotte)',
    'Dzaoudzi (Mayotte)',
    'Male (Maldives)',
    'Maafushi (Maldives)',
    'Hulhumale (Maldives)',
    'Addu City (Maldives)',
    'Thulusdhoo (Maldives)',
    'Eydhafushi (Maldives)',
    'Victoria (Seychelles)',
    'Anse Royale (Seychelles)',
    'Beau Vallon (Seychelles)',
    'La Digue (Seychelles)',
    'Praslin (Seychelles)',
    'Mahe (Seychelles)',
    'Zanzibar City (Tanzania)',
    'Stone Town (Tanzania)',
    'Nungwi (Tanzania)',
    'Paje (Tanzania)',
    'Chake-Chake (Tanzania)',
    'Mkoani (Tanzania)',
    'Saint Helier (Jersey)',
    'Saint Peter Port (Guernsey)',
    'Saint Anne (Alderney)',
    'Saint George (Alderney)',
    'Douglas (Isle of Man)',
    'Peel (Isle of Man)',
    'Castletown (Isle of Man)',
    'Alghero (Italy)',
    'Cagliari (Italy)',
    'Sassari (Italy)',
    'Olbia (Italy)',
    'Oristano (Italy)',
    'Palermo (Italy)',
    'Catania (Italy)',
    'Messina (Italy)',
    'Syracuse (Italy)',
    'Taormina (Italy)',
    'Lipari (Italy)',
    'Lampedusa (Italy)',
    'Ibiza Town (Spain)',
    'Santa Eularia des Riu (Spain)',
    'Sant Antoni de Portmany (Spain)',
    'Palma (Spain)',
    'Alcudia (Spain)',
    'Soller (Spain)',
    'Port de Pollenca (Spain)',
    'Ciutadella (Spain)',
    'Mahon (Spain)',
    'Es Castell (Spain)',
    'Formentera (Spain)',
    'Valletta (Malta)',
    "St. Julian's (Malta)",
    'Sliema (Malta)',
    'Mellieha (Malta)',
    'Gozo (Malta)',
    'Victoria (Malta)',
    'Mdina (Malta)',
    'Protaras (Cyprus)',
    'Ayia Napa (Cyprus)',
    'Paphos (Cyprus)',
    'Limassol (Cyprus)',
    'Larnaca (Cyprus)',
    'Nicosia (Cyprus)',
    'Famagusta (Cyprus)',
    'Kyrenia (Cyprus)',
    'Mykonos Town (Greece)',
    'Fira (Greece)',
    'Oia (Greece)',
    'Parikia (Greece)',
    'Naxos (Greece)',
    'Rethymno (Greece)',
    'Chania (Greece)',
    'Heraklion (Greece)',
    'Agios Nikolaos (Greece)',
    'Kos Town (Greece)',
    'Rhodes Town (Greece)',
    'Lindos (Greece)',
    'Thasos (Greece)',
    'Skopelos (Greece)',
    'Corfu Town (Greece)',
    'Dubrovnik (Croatia)',
    'Split (Croatia)',
    'Hvar (Croatia)',
    'Korcula (Croatia)',
    'Vis (Croatia)',
    'Krk (Croatia)',
    'Rijeka (Croatia)',
    'Funchal (Portugal)',
    'Porto Santo (Portugal)',
    'Santa Cruz de Tenerife (Spain)',
    'Las Palmas (Spain)',
    'Arrecife (Spain)',
    'Playa Blanca (Spain)',
    'Puerto del Carmen (Spain)',
    'Corralejo (Spain)',
    'Costa Calma (Spain)',
    'Morro Jable (Spain)',
    'Adeje (Spain)',
    'Puerto de la Cruz (Spain)',
    'La Palma (Spain)',
    'El Hierro (Spain)',
    'La Gomera (Spain)',
    'Noumea (New Caledonia)',
    'Bora Bora (French Polynesia)',
    'Papeete (French Polynesia)',
    'Moorea (French Polynesia)',
    'Raiatea (French Polynesia)',
    'Apia (Samoa)',
    'Pago Pago (American Samoa)',
    "Nuku'alofa (Tonga)",
    'Suva (Fiji)',
    'Nadi (Fiji)',
    'Lautoka (Fiji)',
    'Port Vila (Vanuatu)',
    'Luganville (Vanuatu)',
    'Avarua (Cook Islands)',
    'Rarotonga (Cook Islands)',
    'Aitutaki (Cook Islands)',
    'Tarawa (Kiribati)',
    'Funafuti (Tuvalu)',
    'Yaren (Nauru)',
    'Majuro (Marshall Islands)',
    'Hanga Roa (Chile)',
    'Kingstown (Saint Vincent and the Grenadines)',
    'Vieux Fort (Saint Lucia)',
    'Port Elizabeth (Saint Vincent and the Grenadines)',
    'Canouan (Saint Vincent and the Grenadines)',
    'Bequia (Saint Vincent and the Grenadines)',
    'Charlestown (Saint Kitts and Nevis)',
    'Plymouth (Montserrat)',
    'Brades (Montserrat)',
    'The Valley (Anguilla)',
    'Gustavia (Saint Barthelemy)',
    'Philipsburg (Sint Maarten)',
    'Cockburn Town (Turks and Caicos)',
    'Providenciales (Turks and Caicos)',
    'Grand Turk (Turks and Caicos)',
    'Willemstad (Curacao)',
    'Kralendijk (Bonaire)',
    'Oranjestad (Aruba)',
    'Kingstown (Saint Vincent and the Grenadines)',
    'Scarborough (Trinidad and Tobago)',
    'Castries (Saint Lucia)',
    'Basseterre (Saint Kitts and Nevis)',
    'Havana (Cuba)',
    'Santiago de Cuba (Cuba)',
    'Cienfuegos (Cuba)',
    'Varadero (Cuba)',
    'Cozumel (Mexico)',
    'Isla Mujeres (Mexico)',
    'Holbox (Mexico)',
    'San Miguel de Cozumel (Mexico)',
    'Key West (USA)',
    'South Padre Island (USA)',
    'Islamorada (USA)',
    'St. Petersburg (USA)',
    'Clearwater (USA)',
    'Anna Maria Island (USA)',
    'Boca Grande (USA)',
    'Marco Island (USA)',
    'Sanibel Island (USA)',
    'Captiva Island (USA)',
    'Prince Edward Island (Canada)',
    'Victoria (Canada)',
    'Nanaimo (Canada)',
    'Tofino (Canada)',
    'Ucluelet (Canada)',
    "St. John's (Canada)",
    'Corner Brook (Canada)',
    'Happy Valley-Goose Bay (Canada)',
    'Charlottetown (Canada)',
    'Cavendish (Canada)',
    'Summerside (Canada)',
    'Magog (Canada)',
    'Iles-de-la-Madeleine (Canada)',
    'Florianopolis (Brazil)',
    'Ilha Grande (Brazil)',
    'Fernando de Noronha (Brazil)',
    'Salvador (Brazil)',
    'Recife (Brazil)',
    'Fortaleza (Brazil)',
    'Natal (Brazil)',
    'Rio de Janeiro (Brazil)',
    'Sao Paulo (Brazil)',
    'Punta del Este (Uruguay)',
    'Isla de Margarita (Venezuela)',
    'Coche Island (Venezuela)',
    'Los Roques (Venezuela)',
    'Aruba (Aruba)',
    'Curacao (Curacao)'
  ]

  return sample(cities, amount).join(', ')
}
